id = "chris-recommended"
name = "Chris's Recommended Collection"

[selections]
"mod:bg1ub" = "on"
"feature:bg1ub:component-0" = "on"
"feature:bg1ub:component-11" = "on"
"feature:bg1ub:component-12" = "on"
"feature:bg1ub:component-13" = "on"
"feature:bg1ub:component-14" = "on"
"feature:bg1ub:component-16" = "on"
"feature:bg1ub:component-17" = "on"
"feature:bg1ub:component-18" = "on"
"feature:bg1ub:component-19" = "on"
"feature:bg1ub:component-21" = "on"
"feature:bg1ub:component-22" = "on"
"feature:bg1ub:component-29" = "on"
"feature:bg1ub:component-30" = "on"
"feature:bg1ub:component-32" = "on"
"feature:bg1ub:component-33" = "on"
"feature:bg1ub:component-34" = "on"
"mod:bg1npc" = "on"
"feature:bg1npc:component-0" = "on"
"feature:bg1npc:component-10" = "on"
"feature:bg1npc:component-90" = "on"
"feature:bg1npc:component-111" = "on"
"feature:bg1npc:component-120" = "on"
"feature:bg1npc:component-130" = "on"
"feature:bg1npc:component-240" = "on"
"feature:bg1npc:component-160" = "on"
"feature:bg1npc:component-200" = "on"
"feature:eet:component-100" = "on"
"mod:eeex" = "on"
"feature:bubb-spell-menu-extended:component-0" = "on"
"feature:bggo:component-0" = "on"
"feature:rr:component-0" = "on"
"feature:rr:component-3" = "on"
"feature:rr:component-7" = "on"
"feature:rr:component-8" = "on"
"feature:rr:component-11" = "on"
"feature:rr:component-12" = "on"
"feature:rr:component-999" = "on"
"mod:evandra" = "on"
"mod:fade" = "on"
"mod:paina" = "on"
"mod:sarahtob" = "on"
"feature:ub:component-0" = "on"
"feature:ub:component-1" = "on"
"feature:ub:component-2" = "on"
"feature:ub:component-4" = "on"
"feature:ub:component-5" = "on"
"feature:ub:component-6" = "on"
"feature:ub:component-7" = "on"
"feature:ub:component-8" = "on"
"feature:ub:component-9" = "on"
"feature:ub:component-10" = "on"
"feature:ub:component-12" = "on"
"feature:ub:component-13" = "on"
"feature:ub:component-14" = "on"
"feature:ub:component-15" = "on"
"feature:ub:component-17" = "on"
"feature:ub:component-18" = "on"
"feature:ub:component-20" = "on"
"feature:ub:component-21" = "on"
"feature:ub:component-25" = "on"
"mod:xan" = "on"
"feature:xan:component-1" = "on"
"feature:yeslicknpc:component-1" = "on"
"feature:sirene-bg2:component-0" = "on"
"feature:sirene-bg2:component-2" = "on"
"feature:sirene-bg2:component-5" = "on"
"feature:iepbanters:component-0" = "on"
"feature:iepbanters:component-1" = "on"
"feature:iepbanters:component-2" = "on"
"feature:iepbanters:component-3" = "on"
"feature:iepbanters:component-4" = "on"
"feature:iepbanters:component-5" = "on"
"feature:iepbanters:component-8" = "on"
"feature:crossmodbg2:component-0" = "on"
"feature:crossmodbg2:component-1" = "on"
"feature:crossmodbg2:component-2" = "on"
"feature:hq-soundclips-bg2ee:component-0" = "on"
"mod:ascension" = "on"
"feature:ascension:component-0" = "on"
"feature:ascension:component-10" = "on"
"feature:ascension:component-20" = "on"
"feature:ascension:component-30" = "on"
"feature:ascension:component-50" = "on"
"feature:ascension:component-60" = "on"
"feature:ascension:component-2000" = "on"
"feature:ascension:component-2100" = "on"
"feature:ascension:component-2300" = "on"
"feature:ascension:component-2400" = "on"
"mod:spell-rev" = "on"
"mod:stratagems" = "on"
"feature:stratagems:component-3041" = "on"
"feature:stratagems:component-3540" = "on"
"feature:stratagems:component-4115" = "on"
"feature:stratagems:component-4215" = "on"
"feature:stratagems:component-4218" = "on"
"feature:stratagems:component-4250" = "on"
"mod:randomiser" = "on"
"feature:randomiser:component-500" = "on"
"feature:randomiser:component-530" = "on"
"feature:randomiser:component-540" = "on"
"feature:randomiser:component-560" = "on"
"feature:randomiser:component-570" = "on"
"feature:randomiser:component-9000" = "on"
"feature:randomiser:component-10200" = "on"
"feature:randomiser:component-10210" = "on"
"feature:randomiser:component-10300" = "on"
"mod:chriz-sod-remix" = "on"
"mod:hidden-gameplay-options" = "on"
"feature:hiddengameplayoptions:component-10" = "on"
"feature:hiddengameplayoptions:component-11" = "on"
"feature:hiddengameplayoptions:component-12" = "on"
"feature:hiddengameplayoptions:component-13" = "on"
"feature:hiddengameplayoptions:component-14" = "on"
"feature:hiddengameplayoptions:component-16" = "on"
"feature:hiddengameplayoptions:component-18" = "on"
"feature:hiddengameplayoptions:component-19" = "on"
"feature:hiddengameplayoptions:component-20" = "on"
"feature:hiddengameplayoptions:component-22" = "on"
"feature:hiddengameplayoptions:component-23" = "on"
"feature:hiddengameplayoptions:component-24" = "on"
"feature:hiddengameplayoptions:component-25" = "on"
"feature:hiddengameplayoptions:component-27" = "on"
"feature:hiddengameplayoptions:component-28" = "on"
"feature:hiddengameplayoptions:component-29" = "on"
"feature:hiddengameplayoptions:component-30" = "on"
"feature:hiddengameplayoptions:component-32" = "on"
"feature:hiddengameplayoptions:component-33" = "on"
"feature:hiddengameplayoptions:component-34" = "on"
"feature:hiddengameplayoptions:component-35" = "on"
"feature:hiddengameplayoptions:component-36" = "on"
"feature:hiddengameplayoptions:component-37" = "on"
"feature:hiddengameplayoptions:component-39" = "on"
"feature:hiddengameplayoptions:component-300" = "on"
"feature:hiddengameplayoptions:component-301" = "on"
"feature:hiddengameplayoptions:component-103" = "on"
"mod:buffbot" = "on"
