id = "chris-recommended"
name = "Chris's Recommended Collection"

[selections]
"mod:bg1ub" = "on"
"feature:bg1ub:component-0" = "on"
"feature:bg1ub:component-11" = "on"
"feature:bg1ub:component-12" = "on"
"feature:bg1ub:component-13" = "on"
"feature:bg1ub:component-14" = "on"
"feature:bg1ub:component-16" = "on"
"feature:bg1ub:component-17" = "on"
"feature:bg1ub:component-18" = "on"
"feature:bg1ub:component-19" = "on"
"feature:bg1ub:component-21" = "on"
"feature:bg1ub:component-22" = "on"
"feature:bg1ub:component-29" = "on"
"feature:bg1ub:component-30" = "on"
"feature:bg1ub:component-32" = "on"
"feature:bg1ub:component-33" = "on"
"feature:bg1ub:component-34" = "on"
"mod:bg1npc" = "on"
"feature:bg1npc:component-0" = "on"
"feature:bg1npc:component-10" = "on"
"feature:bg1npc:component-90" = "on"
"feature:bg1npc:component-111" = "on"
"feature:bg1npc:component-120" = "on"
"feature:bg1npc:component-130" = "on"
"feature:bg1npc:component-240" = "on"
"feature:bg1npc:component-160" = "on"
"feature:bg1npc:component-200" = "on"
"feature:eet:component-100" = "on"
